"""
seed_demo.py — generate a realistic backdated history so the dashboard has
something to show on a fresh clone.

This does **not** touch the network. It writes directly to the database the
same rows the real pipeline would have written, simulating hourly snapshots
across the last few weeks with:

* steady audience growth plus occasional churn,
* a diurnal follow pattern (quiet at 04:00 IST, busy at 21:00-23:00 IST), so
  the "Peak Follow Times" analysis has a genuine signal to find,
* a handful of accounts that unfollow and later return, exercising the
  `times_followed` / re-follow path,
* the odd PARTIAL and FAILED snapshot, so the health tab is not uniformly green.

Detection granularity note: `first_detected_at` is the moment a *snapshot saw*
the follower, not the moment they pressed Follow — that instant is not exposed
by Instagram to anyone but the account owner. With hourly snapshots the two are
within an hour of each other, which is why the seeder emits events on snapshot
boundaries rather than inventing sub-hour precision it could not really have.
"""

from __future__ import annotations

import argparse
import logging
import random
from datetime import timedelta

from sqlalchemy import delete
from sqlalchemy.orm import Session

from db import bootstrap, session_scope
from models import (
    EventType,
    Follower,
    FollowerEvent,
    Snapshot,
    SnapshotStatus,
    Target,
)
from timeutils import to_ist, utcnow
from tracker import get_or_create_target, normalise_username

log = logging.getLogger(__name__)

_FIRST = (
    "aarav", "diya", "kabir", "meera", "rohan", "ananya", "vihaan", "ishita",
    "arjun", "saanvi", "dev", "tara", "nikhil", "priya", "yash", "kavya",
    "aditya", "riya", "manav", "neha", "karan", "sana", "veer", "aisha",
    "raghav", "juhi", "omkar", "zara", "harsh", "myra", "siddharth", "anvi",
    "ayaan", "kiara", "reyansh", "aadhya", "atharv", "pari", "shaurya", "navya",
)
_SECOND = (
    "sharma", "verma", "gupta", "singh", "patel", "reddy", "nair", "iyer",
    "bose", "khan", "mehta", "rao", "das", "joshi", "malhotra", "chopra",
    "_07", "_x", "23", "official", "_ig", "99", ".official", "_here",
)

#: Relative follow likelihood by hour of day in IST. Confession-page audiences
#: are overwhelmingly late-evening; the numbers are illustrative, not measured.
_DIURNAL_WEIGHTS = {
    0: 0.55, 1: 0.30, 2: 0.15, 3: 0.08, 4: 0.05, 5: 0.06,
    6: 0.12, 7: 0.22, 8: 0.35, 9: 0.45, 10: 0.50, 11: 0.52,
    12: 0.58, 13: 0.60, 14: 0.55, 15: 0.52, 16: 0.58, 17: 0.68,
    18: 0.80, 19: 0.92, 20: 1.00, 21: 1.00, 22: 0.95, 23: 0.78,
}


def _make_pool(rng: random.Random, size: int) -> list[str]:
    """Deterministic pool of plausible-looking handles."""
    handles: list[str] = []
    seen: set[str] = set()
    while len(handles) < size:
        handle = f"{rng.choice(_FIRST)}{rng.choice(_SECOND)}"
        if rng.random() < 0.25:
            handle += str(rng.randrange(10, 999))
        if handle not in seen:
            seen.add(handle)
            handles.append(handle)
    return handles


def clear_target_history(session: Session, target: Target) -> None:
    """Delete every follower, event and snapshot for one target."""
    session.execute(delete(FollowerEvent).where(FollowerEvent.target_id == target.id))
    session.execute(delete(Snapshot).where(Snapshot.target_id == target.id))
    session.execute(delete(Follower).where(Follower.target_id == target.id))
    session.flush()


def seed_target(
    session: Session,
    username: str,
    *,
    days: int = 21,
    interval_hours: int = 1,
    starting_followers: int = 240,
    seed: int = 20260824,
    reset: bool = True,
) -> Target:
    """Populate one target with `days` of backdated hourly snapshots."""
    username = normalise_username(username)
    rng = random.Random(f"{seed}:{username}")

    target = get_or_create_target(session, username)
    target.full_name = f"{username.replace('_', ' ').replace('.', ' ').title()}"
    target.biography = "Demo profile — synthetic data generated by seed_demo.py"
    target.instagram_user_id = str(rng.randrange(10**9, 10**10))
    target.is_private = False
    target.is_verified = False

    if reset:
        clear_target_history(session, target)

    now = utcnow().replace(minute=0, second=0, microsecond=0)
    start = now - timedelta(days=days)
    total_ticks = int(days * 24 / interval_hours)

    pool = _make_pool(rng, size=starting_followers + total_ticks * 4 + 200)
    pool_cursor = 0

    # --- Seed the initial audience, backdated before the window -----------
    rows: dict[str, Follower] = {}
    for _ in range(starting_followers):
        handle = pool[pool_cursor]
        pool_cursor += 1
        # Spread the founding cohort over the 60 days before tracking began.
        joined = start - timedelta(hours=rng.randrange(1, 24 * 60))
        row = Follower(
            target_id=target.id,
            instagram_username=handle,
            user_id=str(rng.randrange(10**9, 10**10)),
            full_name=handle.replace("_", " ").replace(".", " ").title(),
            profile_pic_url=f"https://picsum.photos/seed/{handle}/150",
            is_private=rng.random() < 0.4,
            is_verified=rng.random() < 0.02,
            first_detected_at=joined,
            last_seen_at=start,
            currently_following=True,
            times_followed=1,
            snapshots_present=1,
        )
        session.add(row)
        rows[handle] = row
    session.flush()

    following: set[str] = set(rows)
    departed: list[str] = []

    # --- Walk the timeline ------------------------------------------------
    for tick in range(total_ticks):
        stamp = start + timedelta(hours=tick * interval_hours)
        # Schedulers jitter; snapshots do not land on exact hour boundaries.
        stamp += timedelta(seconds=rng.randrange(0, 240))
        local_hour = to_ist(stamp).hour
        weight = _DIURNAL_WEIGHTS[local_hour]

        # ~1.5% of runs fail outright (network, rate limit, expired session).
        if rng.random() < 0.015:
            session.add(
                Snapshot(
                    target_id=target.id,
                    timestamp=stamp,
                    total_followers=len(following),
                    captured_followers=0,
                    reported_followers=len(following),
                    status=SnapshotStatus.FAILED,
                    duration_seconds=round(rng.uniform(4.0, 20.0), 2),
                    error_message=rng.choice(
                        [
                            "Rate limited by Instagram (HTTP 429)",
                            "Request timed out after 45.0s",
                            "HTTP 503 from Instagram",
                        ]
                    ),
                )
            )
            continue

        # --- follows -----------------------------------------------------
        gained: list[str] = []
        expected = weight * rng.uniform(0.8, 3.2)
        for _ in range(int(expected) + (1 if rng.random() < expected % 1 else 0)):
            # 12% of new follows are a returning account.
            if departed and rng.random() < 0.12:
                handle = departed.pop(rng.randrange(len(departed)))
                row = rows[handle]
                row.currently_following = True
                row.unfollowed_at = None
                row.times_followed += 1
                row.last_seen_at = stamp
                following.add(handle)
                gained.append(handle)
                continue

            if pool_cursor >= len(pool):
                break
            handle = pool[pool_cursor]
            pool_cursor += 1
            row = Follower(
                target_id=target.id,
                instagram_username=handle,
                user_id=str(rng.randrange(10**9, 10**10)),
                full_name=handle.replace("_", " ").replace(".", " ").title(),
                profile_pic_url=f"https://picsum.photos/seed/{handle}/150",
                is_private=rng.random() < 0.4,
                is_verified=rng.random() < 0.02,
                first_detected_at=stamp,
                last_seen_at=stamp,
                currently_following=True,
                times_followed=1,
                snapshots_present=1,
            )
            session.add(row)
            session.flush()
            rows[handle] = row
            following.add(handle)
            gained.append(handle)

        # --- unfollows ----------------------------------------------------
        lost: list[str] = []
        # Churn is roughly a third of gross growth and less diurnal than follows.
        if following and rng.random() < 0.35 * max(weight, 0.2):
            for _ in range(rng.randint(1, 2)):
                if len(following) <= 10:
                    break
                handle = sorted(following)[rng.randrange(len(following))]
                row = rows[handle]
                row.currently_following = False
                row.unfollowed_at = stamp
                following.discard(handle)
                departed.append(handle)
                lost.append(handle)

        # --- persistence flags for everyone still present -----------------
        for handle in following:
            row = rows[handle]
            row.last_seen_at = stamp
            row.snapshots_present += 1

        session.flush()

        # --- events -------------------------------------------------------
        snapshot = Snapshot(
            target_id=target.id,
            timestamp=stamp,
            total_followers=len(following),
            captured_followers=len(following),
            reported_followers=len(following) + rng.randrange(0, 3),
            new_followers=len(gained),
            lost_followers=len(lost),
            retained_followers=len(following) - len(gained),
            # A few runs come back short — the diff engine marks these PARTIAL.
            status=SnapshotStatus.PARTIAL if rng.random() < 0.02 else SnapshotStatus.SUCCESS,
            duration_seconds=round(rng.uniform(8.0, 55.0), 2),
        )
        session.add(snapshot)
        session.flush()

        for handle in gained:
            session.add(
                FollowerEvent(
                    follower_id=rows[handle].id,
                    target_id=target.id,
                    snapshot_id=snapshot.id,
                    event_type=EventType.FOLLOW,
                    timestamp=stamp,
                    instagram_username=handle,
                )
            )
        for handle in lost:
            session.add(
                FollowerEvent(
                    follower_id=rows[handle].id,
                    target_id=target.id,
                    snapshot_id=snapshot.id,
                    event_type=EventType.UNFOLLOW,
                    timestamp=stamp,
                    instagram_username=handle,
                )
            )

    target.last_scraped_at = now
    target.reported_follower_count = len(following)
    session.flush()
    log.info(
        "Seeded @%s: %d followers now, %d tracked ever, %d snapshots over %d days",
        username,
        len(following),
        len(rows),
        total_ticks,
        days,
    )
    return target


def seed(
    usernames: list[str],
    *,
    days: int = 21,
    interval_hours: int = 1,
    reset: bool = True,
) -> None:
    bootstrap()
    with session_scope() as session:
        for username in usernames:
            seed_target(
                session,
                username,
                days=days,
                interval_hours=interval_hours,
                reset=reset,
            )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "usernames",
        nargs="*",
        default=["campus_confessions", "city_secrets_page"],
        help="Target handles to generate history for.",
    )
    parser.add_argument("--days", type=int, default=21, help="How far back to simulate.")
    parser.add_argument(
        "--interval-hours", type=int, default=1, help="Simulated snapshot interval."
    )
    parser.add_argument(
        "--keep",
        action="store_true",
        help="Append to existing history instead of clearing it first.",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    names = args.usernames or ["campus_confessions", "city_secrets_page"]
    seed(names, days=args.days, interval_hours=args.interval_hours, reset=not args.keep)
    print(f"Seeded {len(names)} target(s). Launch the dashboard with: streamlit run app.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
